myPathToCode = /home/ermartin/StanfordDASArray/IEEEsigproc_ambientDAS/code
#myPathToCode = /CorrelationCode

oneBitXCorr1:
	python calc_oneBitXCorr.py ${myPathToCode}/src/params/params1

plotOneBitXCorr1:
	python plot_oneBitXCorr.py ${myPathToCode}/src/params/params1


plotOneBitXCorrs1:
	python plot_oneBitXCorrs_multi_file_lists.py ${myPathToCode}/src/params/params1plot rasterTestPlot
