oneBitXCorr1:
	python calc_oneBitXCorr.py /home/CorrelationCode/src/params/params1

plotOneBitXCorr1:
	python plot_oneBitXCorr.py /home/CorrelationCode/src/params/params1


plotOneBitXCorrs1To6:
	python plot_oneBitXCorrs_multi_file_lists.py /home/CorrelationCode/src/params/params1plot