xcorrParams:
	python paramsSetup.py

trainingParams:
	python trainingParamsSetup.py

all:
	make xcorrParams
	make trainingParams

clean:
	rm -rf params1*
	rm -rf params2*
	rm -rf params3*
	rm -rf params4*
	rm -rf params5*
	rm -rf params6*
	rm -rf params7*
	rm -rf params8*
	rm -rf params9*
	rm -rf trainingparams*
